### ISSUE TITLE
Does the code handle continuous actions? Or how can it handle a mixed discrete/continuous action space?

### ISSUE THREAD

**Issue by janetwise** [jbr-ai-labs/mamba#8]
Does the code handle continuous actions? Or how can it handle a mixed discrete/continuous action space?

**Comment by vladimirrim** [comment]
No, it is not implemented in the code, but it should be fairly straightforward to add:

- You will need to change [action_information_loss](https://github.com/jbr-ai-labs/mamba/blob/main/agent/optim/utils.py#L60) to MSE loss instead of Cross Entropy
- Change [calculate_ppo_loss](https://github.com/jbr-ai-labs/mamba/blob/main/agent/optim/utils.py#L60) to your continuous distribution

Handling mixed action spaces is a bit more tricky, you will need to have tuple of actions both in [RSSMTransition](https://github.com/jbr-ai-labs/mamba/blob/main/networks/dreamer/rnns.py#L39) and [transition buffer](https://github.com/jbr-ai-labs/mamba/blob/main/agent/memory/DreamerMemory.py) since they have different dimensions, as well as two embedding functions in RSSMTransition model to transform actions to the same shape
